language: node_js
node_js:
    - stable
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - npm install
script:
    - npm run build
    - npm run karma
cache:
    directories:
        - node_modules
notifications:
    email: false
